function compute_plot_spectrum(cfg)
run(cfg.path_conditions);
n_cnd = length(cnds);
elec_labels = arrayfun(@(x) erase(x.name, '.mat'), cfg.mat, 'uni', 0);
n_elec      = length(elec_labels);
n_frq = size(cfg.computation.f_bands, 1);
for i_cnd = 1:n_cnd
    metric = cell(n_elec, 1);
    n_brst = cell(n_elec, 1);
    n_trl = NaN(n_elec, 1);

    cfg.computation.trialfilter = cnds(i_cnd).trialfilter;
    parfor i_elec = 1:n_elec
        cfg.computation.filename = fullfile(cfg.mat(i_elec).folder, cfg.mat(i_elec).name);
        [metric{i_elec}, n_trl(i_elec), n_brst{i_elec}] = burstmetric_computation(cfg.computation);
    end

    % plotting
    metric = cell2mat(cellfun(@(x) reshape(x, [1 size(x)]), metric, 'uni', 0));
    n_brst = cell2mat(n_brst);
    for i_mtype = 1:numel(cfg.mtype)
        for i_elec = 1:n_elec
            cfg.plot.annotation.string = ...
                strrep(horzcat(...
                    elec_labels{i_elec}, ... 
                    newline, cfg.mtype(i_mtype).fullname, ...
                    newline, cnds(i_cnd).name, ...
                    cfg.plot.figtext), '_', '\_');
            cfg.plot.save.fullpath = fullfile(...
                cfg.plot.save.figfolder,...
                cfg.mtype(i_mtype).abbreviation,...
                cnds(i_cnd).relfolder,...
                sprintf('%s_%s', cnds(i_cnd).name, elec_labels{i_elec}));

            plot_spectrum(cfg.plot, squeeze(metric(i_elec,i_mtype,1:(n_frq-1),:)));
            close all;

        end
        cfg.plot.annotation.string = ...
            strrep(horzcat(...
                'mean across electrodes', ... 
                newline, cfg.mtype(i_mtype).fullname, ...
                newline, cnds(i_cnd).name, ...
                cfg.plot.figtext), '_', '\_');
        cfg.plot.save.fullpath = fullfile(...
            cfg.plot.save.figfolder,...
            cfg.mtype(i_mtype).abbreviation,...
            cnds(i_cnd).relfolder,...
            sprintf('%s_%s', cnds(i_cnd).name, 'mean'));

        plot_spectrum(cfg.plot, squeeze(mean(metric(n_trl>=cfg.plot.min_trl,i_mtype,1:(n_frq-1),:), 1)));
        close all
    end
end
